name: Feature Request
description: Suggest an improvement or new feature
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Tell us what you want and why.

  - type: textarea
    id: request
    attributes:
      label: Feature Summary
      placeholder: What feature do you want added?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why is this needed?
      placeholder: Why would this feature be useful?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional Details (optional)
      placeholder: Extra context or ideas about implementation...
